language: php

php:
    - "5.3"
    - "5.4"
    - "5.5"
    - "5.6"
    - "hhvm"

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=3.8 WP_MULTISITE=0
    - WP_VERSION=3.8 WP_MULTISITE=1

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    - pear install --alldeps PHP_CodeSniffer
    - phpenv rehash
    - git clone git://github.com/mrchrisadams/WordPress-Coding-Standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress
    ## PHP Copy/Paste Detector
    - curl -o phpcpd.phar https://phar.phpunit.de/phpcpd.phar
    ## PHP Mess Detector
    - pear config-set preferred_state beta
    - printf "\n" | pecl install imagick
    - pear channel-discover pear.phpmd.org
    - pear channel-discover pear.pdepend.org
    - pear install --alldeps phpmd/PHP_PMD
    - pear channel-discover pear.phing.info
    - pear install phing/phing
    - phpenv rehash
    ## PHPLOC
    - curl -o phploc.phar https://phar.phpunit.de/phploc.phar

script:
    - phing build:travis
